let mock = [{
  id: 1,
  year: 2019,
  make: "Toyota",
  model: "Corolla",
  price: "$18,700",
  mpg: 32,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/toyota/corolla.jpg"
},
{
  id: 2,
  year: 2017,
  make: "Toyota",
  model: "Camry",
  price: "$15,700",
  mpg: 27,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/toyota/camry.jpg"
},
{
  id: 3,
  year: 2019,
  make: "Toyota",
  model: "Rav4",
  price: "$25,650",
  mpg: 28,
  seats: 5,
  drivetrain: "AWD",
  image: "/images/toyota/rav4.jpg"
},
{
  id: 4,
  year: 2018,
  make: "Toyota",
  model: "C-HR",
  price: "$18,750",
  mpg: 29,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/toyota/c-hr.jpg"
},
{
  id: 5,
  year: 2017,
  make: "Honda",
  model: "CR-V",
  price: "$20,200",
  mpg: 29,
  seats: 5,
  drivetrain: "AWD",
  image: "/images/honda/cr-v.jpg"
},
{
  id: 6,
  year: 2018,
  make: "Honda",
  model: "Civic",
  price: "$17,100",
  mpg: 28,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/honda/civic.jpg"
},
{
  id: 7,
  year: 2018,
  make: "Honda",
  model: "Accord",
  price: "$20,100",
  mpg: 30,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/honda/accord.jpg"
},
{
  id: 8,
  year: 2019,
  make: "Honda",
  model: "Pilot",
  price: "$31,500",
  mpg: 25,
  seats: 7,
  drivetrain: "AWD",
  image: "/images/honda/pilot.jpg"
},
{
  id: 9,
  year: 2018,
  make: "Honda",
  model: "Odyssey",
  price: "$24,800",
  mpg: 26,
  seats: 7,
  drivetrain: "AWD",
  image: "/images/honda/odyssey.jpg"
},
{
  id: 10,
  year: 2019,
  make: "Hyundai",
  model: "Elantra",
  price: "$18,000",
  mpg: 28,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/hyundai/elantra.jpg"
},
{
  id: 11,
  year: 2018,
  make: "Hyundai",
  model: "Kona",
  price: "$16,500",
  mpg: 28,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/hyundai/kona.jpg"
},
{
  id: 12,
  year: 2018,
  make: "Hyundai",
  model: "Tucson",
  price: "$17,050",
  mpg: 26,
  seats: 5,
  drivetrain: "AWD",
  image: "/images/hyundai/tucson.jpg"
},
{
  id: 13,
  year: 2020,
  make: "Hyundai",
  model: "Palisade",
  price: "$31,800",
  mpg: 21,
  seats: 7,
  drivetrain: "AWD",
  image: "/images/hyundai/palisade.jpg"
},
{
  id: 14,
  year: 2020,
  make: "Hyundai",
  model: "SantaFe",
  price: "$26,100",
  mpg: 24,
  seats: 5,
  drivetrain: "AWD",
  image: "/images/hyundai/santafe.jpg"
},
{
  id: 15,
  year: 2019,
  make: "Ford",
  model: "Edge",
  price: "$29,900",
  mpg: 24,
  seats: 5,
  drivetrain: "AWD",
  image: "/images/ford/edge.jpg"
},
{
  id: 16,
  year: 2020,
  make: "Ford",
  model: "Explorer",
  price: "$36,600",
  mpg: 23,
  seats: 5,
  drivetrain: "AWD",
  image: "/images/ford/explorer.jpg"
},
{
  id: 17,
  year: 2019,
  make: "Ford",
  model: "F-250",
  price: "$31,000",
  mpg: 15,
  seats: 5,
  drivetrain: "4WD",
  image: "/images/ford/f250.jpg"
},
{
  id: 18,
  year: 2019,
  make: "Ford",
  model: "Expedition",
  price: "$52,000",
  mpg: 20,
  seats: 7,
  drivetrain: "AWD",
  image: "/images/ford/expedition.jpg"
},
{
  id: 19,
  year: 2018,
  make: "Ford",
  model: "Mustang",
  price: "$21,700",
  mpg: 20,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/ford/mustang.jpg"
},
{
  id: 20,
  year: 2018,
  make: "Ford",
  model: "Escape",
  price: "$17,100",
  mpg: 27,
  seats: 5,
  drivetrain: "AWD",
  image: "/images/ford/escape.jpg"
},
{
  id: 21,
  year: 2015,
  make: "Chevrolet",
  model: "Tahoe",
  price: "$28,500",
  mpg: 18,
  seats: 7,
  drivetrain: "AWD",
  image: "/images/chevrolet/tahoe.jpg"
},
{
  id: 22,
  year: 2019,
  make: "Chevrolet",
  model: "Camaro",
  price: "$25,000",
  mpg: 20,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/chevrolet/camaro.jpg"
},
{
  id: 23,
  year: 2014,
  make: "Chevrolet",
  model: "Silverado",
  price: "$14,200",
  mpg: 18,
  seats: 5,
  drivetrain: "4WD",
  image: "/images/chevrolet/silverado.jpg"
},
{
  id: 24,
  year: 2018,
  make: "Chevrolet",
  model: "Corvette",
  price: "$41,300",
  mpg: 20,
  seats: 2,
  drivetrain: "RWD",
  image: "/images/chevrolet/corvette.jpg"
},
{
  id: 25,
  year: 2017,
  make: "Mazda",
  model: "CX-5",
  price: "$19,400",
  mpg: 27,
  seats: 5,
  drivetrain: "AWD",
  image: "/images/mazda/cx-5.jpg"
},
{
  id: 26,
  year: 2017,
  make: "Mazda",
  model: "CX-9",
  price: "$22,700",
  mpg: 25,
  seats: 7,
  drivetrain: "AWD",
  image: "/images/mazda/cx-9.jpg"
},
{
  id: 27,
  year: 2019,
  make: "Mazda",
  model: "3",
  price: "$21,500",
  mpg: 30,
  seats: 5,
  drivetrain: "FWD",
  image: "/images/mazda/3.jpg"
}]

export default mock;
