let mock = [{
  id: 1,
  year: 2019,
  make: "Toyota",
  model: "Corolla",
  price: "$18,700",
  mpg: 32,
  seats: 5,
  drivetrain: "FWD",
  image: "Toyota/Corolla.jpg"
},
{
  id: 2,
  year: 2017,
  make: "Toyota",
  model: "Camry",
  price: "$15,700",
  mpg: 27,
  seats: 5,
  drivetrain: "FWD",
  image: "Toyota/Camry.jpg"
},
{
  id: 3,
  year: 2019,
  make: "Toyota",
  model: "Rav4",
  price: "$25,650",
  mpg: 28,
  seats: 5,
  drivetrain: "AWD",
  image: "Toyota/Rav4.jpg"
},
{
  id: 4,
  year: 2018,
  make: "Toyota",
  model: "C-HR",
  price: "$18,750",
  mpg: 29,
  seats: 5,
  drivetrain: "FWD",
  image: "Toyota/C-HR.jpg"
},
{
  id: 5,
  year: 2017,
  make: "Honda",
  model: "CR-V",
  price: "$20,200",
  mpg: 29,
  seats: 5,
  drivetrain: "AWD",
  image: "Honda/CR-V.jpg"
},
{
  id: 6,
  year: 2018,
  make: "Honda",
  model: "Civic",
  price: "$17,100",
  mpg: 28,
  seats: 5,
  drivetrain: "FWD",
  image: "Honda/Civic.jpg"
},
{
  id: 7,
  year: 2018,
  make: "Honda",
  model: "Accord",
  price: "$20,100",
  mpg: 30,
  seats: 5,
  drivetrain: "FWD",
  image: "Honda/Accord.jpg"
},
{
  id: 8,
  year: 2019,
  make: "Honda",
  model: "Pilot",
  price: "$31,500",
  mpg: 25,
  seats: 7,
  drivetrain: "AWD",
  image: "Honda/Pilot.jpg"
},
{
  id: 9,
  year: 2018,
  make: "Honda",
  model: "Odyssey",
  price: "$24,800",
  mpg: 26,
  seats: 7,
  drivetrain: "AWD",
  image: "Honda/Odyssey.jpg"
},
{
  id: 10,
  year: 2019,
  make: "Hyundai",
  model: "Elantra",
  price: "$18,000",
  mpg: 28,
  seats: 5,
  drivetrain: "FWD",
  image: "Hyundai/Elantra.jpg"
},
{
  id: 11,
  year: 2018,
  make: "Hyundai",
  model: "Kona",
  price: "$16,500",
  mpg: 28,
  seats: 5,
  drivetrain: "FWD",
  image: "Hyundai/Kona.jpg"
},
{
  id: 12,
  year: 2018,
  make: "Hyundai",
  model: "Tucson",
  price: "$17,050",
  mpg: 26,
  seats: 5,
  drivetrain: "AWD",
  image: "Hyundai/Tucson.jpg"
},
{
  id: 13,
  year: 2020,
  make: "Hyundai",
  model: "Palisade",
  price: "$31,800",
  mpg: 21,
  seats: 7,
  drivetrain: "AWD",
  image: "Hyundai/Palisade.jpg"
},
{
  id: 14,
  year: 2020,
  make: "Hyundai",
  model: "Santa Fe",
  price: "$26,100",
  mpg: 24,
  seats: 5,
  drivetrain: "AWD",
  image: "Hyundai/SantaFe.jpg"
},
{
  id: 15,
  year: 2019,
  make: "Ford",
  model: "Edge",
  price: "$29,900",
  mpg: 24,
  seats: 5,
  drivetrain: "AWD",
  image: "Ford/Edge.jpg"
},
{
  id: 16,
  year: 2020,
  make: "Ford",
  model: "Explorer",
  price: "$36,600",
  mpg: 23,
  seats: 5,
  drivetrain: "AWD",
  image: "Ford/Explorer.jpg"
},
{
  id: 17,
  year: 2019,
  make: "Ford",
  model: "F-250",
  price: "$31,000",
  mpg: 15,
  seats: 5,
  drivetrain: "4WD",
  image: "Ford/F250.jpg"
},
{
  id: 18,
  year: 2019,
  make: "Ford",
  model: "Expedition",
  price: "$52,000",
  mpg: 20,
  seats: 7,
  drivetrain: "AWD",
  image: "Ford/Expedition.jpg"
},
{
  id: 19,
  year: 2018,
  make: "Ford",
  model: "Mustang",
  price: "$21,700",
  mpg: 20,
  seats: 5,
  drivetrain: "FWD",
  image: "Ford/Mustang.jpg"
},
{
  id: 20,
  year: 2018,
  make: "Ford",
  model: "Escape",
  price: "$17,100",
  mpg: 27,
  seats: 5,
  drivetrain: "AWD",
  image: "Ford/Escape.jpg"
},
{
  id: 21,
  year: 2015,
  make: "Chevrolet",
  model: "Tahoe",
  price: "$28,500",
  mpg: 18,
  seats: 7,
  drivetrain: "AWD",
  image: "Chevrolet/Tahoe.jpg"
},
{
  id: 22,
  year: 2019,
  make: "Chevrolet",
  model: "Camaro",
  price: "$25,000",
  mpg: 20,
  seats: 5,
  drivetrain: "FWD",
  image: "Chevrolet/Camaro.jpg"
},
{
  id: 23,
  year: 2014,
  make: "Chevrolet",
  model: "Silverado",
  price: "$14,200",
  mpg: 18,
  seats: 5,
  drivetrain: "4WD",
  image: "Chevrolet/Silverado.jpg"
},
{
  id: 24,
  year: 2018,
  make: "Chevrolet",
  model: "Corvette",
  price: "$41,300",
  mpg: 20,
  seats: 2,
  drivetrain: "RWD",
  image: "Chevrolet/Corvette.jpg"
},
{
  id: 25,
  year: 2017,
  make: "Mazda",
  model: "CX-5",
  price: "$19,400",
  mpg: 27,
  seats: 5,
  drivetrain: "AWD",
  image: "Mazda/CX-5.jpg"
},
{
  id: 26,
  year: 2017,
  make: "Mazda",
  model: "CX-9",
  price: "$22,700",
  mpg: 25,
  seats: 7,
  drivetrain: "AWD",
  image: "Mazda/CX-9.jpg"
},
{
  id: 27,
  year: 2019,
  make: "Mazda",
  model: "3",
  price: "$21,500",
  mpg: 30,
  seats: 5,
  drivetrain: "FWD",
  image: "Mazda/3.jpg"
}]

export default mock;
